echo "Testing program output with ilocsim.py simulator:"
echo ""

cd ..
make clean
make

# Executes program against tests and create output .iloc files
./etapa5 < tests/declaration.c > tests/output/declaration.iloc
./etapa5 < tests/empty.c > tests/output/empty.iloc
./etapa5 < tests/fibo.c > tests/output/fibo.iloc
./etapa5 < tests/one_function.c > tests/output/one_function.iloc

echo ""
echo "Intermedaite code generate"
echo "Running ilocsim.py simulator:"
echo ""

# Executes iloc files generated by program against the simulator and create .sim output files
python3 scripts/ilocsim.py -x -t -s --data 500 --stack 1024 tests/output/declaration.iloc > scripts/ilocsim_output/declaration.sim
python3 scripts/ilocsim.py -x -t -s --data 500 --stack 1024 tests/output/empty.iloc > scripts/ilocsim_output/empty.sim
python3 scripts/ilocsim.py -x -t -s --data 500 --stack 1024 tests/output/fibo.iloc > scripts/ilocsim_output/fibo.sim
python3 scripts/ilocsim.py -x -t -s --data 500 --stack 1024 tests/output/one_function.iloc > scripts/ilocsim_output/one_function.sim

echo ""
echo "ilocsim simulator ended"
echo "Results on scripts/ilocsim_output folder"

